### ISSUE TITLE
ZipUtility-v1.1.1-UE5.1 deploy android error

### ISSUE THREAD

**Issue by zhuziying** [getnamo/ZipUtility-ue4#52]
Running d:\Program Files\Epic Games\UE_5.1\Engine\Build\BatchFiles\Build.bat -Target="RedStoryEditor Win64 Development -Project=""d:/Unreal Projects/RedStory/RedStory.uproject""" -LiveCoding -LiveCodingModules="d:/Program Files/Epic Games/UE_5.1/Engine/Intermediate/LiveCodingModules.txt" -LiveCodingManifest="d:/Program Files/Epic Games/UE_5.1/Engine/Intermediate/LiveCoding.json" -WaitMutex -LiveCodingLimit=100
  Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" -Target="RedStoryEditor Win64 Development -Project=""d:/Unreal Projects/RedStory/RedStory.uproject""" -LiveCoding -LiveCodingModules="d:/Program Files/Epic Games/UE_5.1/Engine/Intermediate/LiveCodingModules.txt" -LiveCodingManifest="d:/Program Files/Epic Games/UE_5.1/Engine/Intermediate/LiveCoding.json" -WaitMutex -LiveCodingLimit=100
  Log file: C:\Users\Administrator\AppData\Local\UnrealBuildTool\Log.txt
  Using 'git status' to determine working set for adaptive non-unity build (D:\Unreal Projects\RedStory).
  Invalidating makefile for RedStoryEditor (source file removed)
  ZipUtility Info: Using default VS path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
  ZipUtility Error: can't find VS path: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC'.
     at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
     at System.IO.Enumeration.FileSystemEnumerator`1.Init()
     at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
     at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
     at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
     at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
     at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
     at System.IO.Directory.GetDirectories(String path)
     at ZipUtility.get_ATLPath() in D:\Unreal Projects\RedStory\Plugins\ZipUtility-Unreal\Source\ZipUtility\ZipUtility.Build.cs:line 44
  ZipUtility Error: Couldn't find an ATLPath, fix it in ZipUtility.Build.cs
  ZipUtility Info: Using ATL path

**Comment by getnamo** [comment]
This repo only supports windows platform atm. You likely want to use the built-in zlib library: https://forums.unrealengine.com/t/how-to-use-zlib-library-in-android-project/489988
